apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecit-web-service
  namespace: wlb965
spec:
  selector:
    matchLabels:
      app: kubecit-web-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kubecit-web-service
    spec:
      containers:
        - name: kubecit-web-service
          image: z627062293/cit965-frontend:v1.0.0 # {"$imagepolicy": "wlb965:kubecit-web"}
          ports:
            - containerPort: 80
